# Configurações gerais
threads: 1
arquivo_input: dados.txt
timeout_padrao: 25
headless: false
salvar_capturas: false

# Login
mail_user_email: "seguroviagemcomparativo@gmail.com"
mail_app_password: "azpmnxqsgsxjgzma"
imap_server: imap.gmail.com

# Proxy
usar_proxy: true
proxy_extension_path: "./utilitarios/proxy"
