# Configurações gerais
threads: 1
arquivo_input: dados.txt
timeout_padrao: 25
headless: false
salvar_capturas: false

# Login
login_email: "o.natan1907@gmail.com"
login_senha: "Natan@11"
login_refresh_interval: 3

# Proxy
usar_proxy: true
proxy_extension_path: "./utilitarios/proxy"
