navegadores_simultaneos: 4
arquivo_input: dados.txt
token: 29cfd95b1e9c6a0d72d8ae935595aeda
login: kiolaspbtt@hotmail.com
senha: rilokiskps2!
salvar_login: false
usar_proxy: true
resolver_captcha: false