# Configurações gerais
threads: 1
arquivo_input: dados.txt
timeout_padrao: 25
headless: false
salvar_capturas: false

# Login
login_email: "albertoramanmelo@hotmail.com"
login_senha: "sucesso1234"

# Proxy
usar_proxy: true
proxy_extension_path: "./utilitarios/proxy"
